#
# This pgpkg file manages pgpkg's own schema.
# The pgpkg schema tracks the current state of the database
# and allows us to know which updates need to be applied.
#

#
# The unique name for this package.
# Currently a Go module name.
#
Package = "github.com/pgpkg/pgpkg"

#
# The schema managed by this package.
# Schema ownership is managed by Pgpkg. If a schema
# already exists and is not owned by a Pgpkg package,
# or is owned by some other Pgpkg package, then
# the upgrade will be aborted.
#
Schemas = [ "pgpkg" ]

#
# Extensions required by this package
#
# Extensions = []

#
# Other packages used by this package.
#
# Uses = []

#
# Lists the migration scripts, in order.
# Migrations are run in order, one at a time.
# Each migration script is uniquely identified by its *filename*.
# You can NOT have two migration scripts with the same filename,
# even if they are on different paths. This restriction, however, makes it easy
# to move migration scripts around in the project.
Migrations = [
    "schema/mob.sql",
    "schema/migration.sql",
    "schema/pkg.sql",
    "schema/testops_numeric.sql",
    "schema/testops_integer.sql",
    "schema/testops_text.sql",
    "schema/testops_timestamptz.sql",
    "schema/testops_boolean.sql",
    "schema/testops_bigint.sql",
    "schema/testops_uuid.sql",
    "schema/testops_jsonb.sql",
    "schema/migration@001.sql"
]