#
# This pgpkg file manages pgpkg's own schema.
# The pgpkg schema tracks the current state of the database
# and allows us to know which updates need to be applied.
#

#
# The unique name for this package.
# Currently a Go module name.
#
Package = "github.com/bookwork/pgpkg"

#
# The schema managed by this package.
# Schema ownership is managed by Pgpkg. If a schema
# already exists and is not owned by a Pgpkg package,
# or is owned by some other Pgpkg package, then
# the upgrade will be aborted.
#
Schema = "pgpkg"

#
# Extensions required by this package
#
# Extensions = []

#
# Other packages used by this package.
#
# Uses = []