name: Release

on:
  push:
    tags:
      - "v*.*.*"  # Trigger only on tags, following a versioning scheme

jobs:
  release:
    name: Build and Release with GoReleaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for GoReleaser

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Your Go version

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: 'latest'
          args: release --skip=homebrew  # Skips the Homebrew release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}